#!/usr/bin/env bash
#
# Setup script for Compliance-as-Code Enforcer
# Installs dependencies and configures the environment
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

check_command() {
    if ! command -v "$1" &> /dev/null; then
        return 1
    fi
    return 0
}

info "Starting Compliance-as-Code Enforcer setup..."

# Check prerequisites
info "Checking prerequisites..."

if ! check_command terraform; then
    error "Terraform not found. Install from: https://www.terraform.io/downloads"
fi

if ! check_command opa; then
    warn "OPA not found. Attempting to install..."
    if check_command brew; then
        brew install opa
    else
        error "Please install OPA manually: https://www.openpolicyagent.org/docs/latest/#running-opa"
    fi
fi

if ! check_command conftest; then
    warn "Conftest not found. Attempting to install..."
    if check_command brew; then
        brew install conftest
    else
        error "Please install Conftest manually: https://www.conftest.dev/install/"
    fi
fi

if ! check_command aws; then
    error "AWS CLI not found. Install from: https://aws.amazon.com/cli/"
fi

if ! check_command python3; then
    error "Python 3 not found. Install Python >= 3.11"
fi

info "All prerequisites satisfied!"

# Verify AWS credentials
info "Verifying AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    error "AWS credentials not configured. Run: aws configure"
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
REGION=$(aws configure get region || echo "us-east-1")
info "AWS Account: $ACCOUNT_ID | Region: $REGION"

# Create terraform backend configuration
info "Setting up Terraform backend..."

BACKEND_BUCKET="compliance-enforcer-state-${ACCOUNT_ID}"
BACKEND_TABLE="compliance-enforcer-locks"

cat > terraform/backend/backend.tf << EOF
# Auto-generated by setup.sh
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "${REGION}"

  default_tags {
    tags = {
      Project     = "compliance-as-code-enforcer"
      ManagedBy   = "terraform"
      Environment = "shared"
    }
  }
}

resource "aws_s3_bucket" "terraform_state" {
  bucket = "${BACKEND_BUCKET}"

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_s3_bucket_versioning" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "terraform_state" {
  bucket = aws_s3_bucket.terraform_state.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_dynamodb_table" "terraform_locks" {
  name         = "${BACKEND_TABLE}"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }
}

output "backend_bucket" {
  value = aws_s3_bucket.terraform_state.id
}

output "lock_table" {
  value = aws_dynamodb_table.terraform_locks.id
}
EOF

info "Initializing Terraform backend..."
cd terraform/backend
terraform init
terraform apply -auto-approve

info "Backend created successfully!"

# Create backend configuration for other modules
cd ../..
cat > terraform/backend.hcl << EOF
# Auto-generated backend configuration
bucket         = "${BACKEND_BUCKET}"
key            = "compliance-enforcer/terraform.tfstate"
region         = "${REGION}"
dynamodb_table = "${BACKEND_TABLE}"
encrypt        = true
EOF

info "Backend configuration saved to terraform/backend.hcl"

# Install Python dependencies
if [ -f lambda/scanner/requirements.txt ]; then
    info "Installing Python dependencies for Lambda scanner..."
    cd lambda/scanner
    pip3 install -r requirements.txt -t ./package/ || warn "Failed to install Python deps (non-critical)"
    cd ../..
fi

# Test policies
info "Testing OPA policies..."
if [ -d policies/soc2 ]; then
    opa test policies/ || warn "Some policy tests failed (expected if policies not yet created)"
fi

info ""
info "========================================"
info "Setup complete! Next steps:"
info "========================================"
info ""
info "1. Review policies in: policies/soc2/"
info "2. Test locally: cd terraform/test-infrastructure && conftest test *.tf --policy ../../policies/soc2/"
info "3. Deploy runtime monitoring: cd terraform/runtime-monitoring && terraform init -backend-config=../backend.hcl && terraform apply"
info ""
info "For more information, see README.md"
